imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $root_path: '%core.root_path%'
            $php_ext: '%core.php_ext%'
            $tables: '%tables%'
            $ext_images_path: '%core.root_path%ext/david63/langgroup/adm/style/images'
        public: true			

    david63.langgroup.listener:
        class: david63\langgroup\event\listener
        tags: [{ name: event.listener }]

    david63.langgroup.main.controller:
        class: david63\langgroup\controller\main_controller

    david63.langgroup.admin.controller:
        class: david63\langgroup\controller\admin_controller

    david63.langgroup.core.functions:
        class: david63\langgroup\core\functions

    david63.langgroup.core.utils:
        class: david63\langgroup\core\utils
